language: python
python:
  - "2.6"
  - "2.7"
#  - "pypy"
env:
  - DJANGO_VERSION=1.3.1
  - DJANGO_VERSION=1.4
before_install:
  - export PIP_USE_MIRRORS=true
  - export PIP_INDEX_URL=https://simple.crate.io/
  - export DJANGO_SETTINGS_MODULE=floppyforms.test_settings
  - sudo apt-get update
  - sudo apt-get install binutils gdal-bin libproj-dev libgeos-c1
install:
  - pip install -e .
  - pip install -r requirements/tests.txt Django==$DJANGO_VERSION
before_script:
  - flake8 floppyforms --ignore=E5,E123,E125,E126
script:
  - make test
branches:
  only:
    - master
notifications:
  irc:
    channels:
      - "irc.freenode.org#django-floppyforms"
    on_success: change
    on_failure: always
